# Generated by Django 6.1.1 on 2026-09-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
        migrations.RemoveField(
            model_name='article',
            name='approved',
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Awaiting approval'), ('APPROVED', 'Approved')], db_index=True, default='DRAFT', max_length=20),
        ),
    ]
