# Generated by Django 6.1.1 on 2026-09-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_article_options_remove_article_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='articles',
            field=models.ManyToManyField(blank=True, limit_choices_to={'status': 'APPROVED'}, related_name='newsletters', to='news.article'),
        ),
    ]
