# Generated by Django 6.1.1 on 2026-09-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0005_store_product_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='verified_purchase',
            field=models.BooleanField(default=False),
        ),
    ]
