# Generated by Django 6.1 on 2026-09-27 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0007_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
