# Generated by Django 6.1.1 on 2026-09-07 13:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grabsomore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resettoken',
            name='expiry_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
